import type { Orvano as ClientOrvano } from '@orvano/js'
import type { Orvano as ServerOrvano } from '@orvano/js/server'

/** A step's `input`: path and query parameters by name, the JSON body under `body`. */
export type ScenarioInput = Record<string, unknown>

/** One operation in the generated dispatch table. */
export interface DispatchEntry {
  /** The success status the contract declares; the SDK returns the body, not the status. */
  status: number
  /** The call through the root entry (`client` and `both` operations). */
  client?: (orvano: ClientOrvano, input: ScenarioInput) => Promise<unknown>
  /** The call through the `./server` entry (`server` and `both` operations). */
  server?: (orvano: ServerOrvano, input: ScenarioInput) => Promise<unknown>
}

/** operationId to its SDK call, generated by SdkGen. */
export type DispatchTable = Record<string, DispatchEntry>
