import type { ClientSurface } from './generated/client.js'
import type { ConsoleSurface } from './generated/console.js'
import type { ServerSurface } from './generated/server.js'

/** A step's `input`: path and query parameters by name, the JSON body under `body`. */
export type ScenarioInput = Record<string, unknown>

/** One operation in a generated dispatch table. */
export interface DispatchEntry {
  /** The success status the contract declares; the SDK returns the body, not the status. */
  status: number
  /** The call through the root entry (`client` and `both` operations). */
  client?: (o: ClientSurface, input: ScenarioInput) => Promise<unknown>
  /** The call through the `./server` entry (`server` and `both` operations). */
  server?: (o: ServerSurface, input: ScenarioInput) => Promise<unknown>
  /** The call through `@orvano/console-client` (`console` operations). */
  console?: (o: ConsoleSurface, input: ScenarioInput) => Promise<unknown>
  /** For a list operation: every item through the root entry's async iterator. */
  clientAll?: (o: ClientSurface, input: ScenarioInput) => AsyncIterable<unknown>
  /** For a list operation: every item through the `./server` entry's async iterator. */
  serverAll?: (o: ServerSurface, input: ScenarioInput) => AsyncIterable<unknown>
  /** For a console list operation: every item through the console client's async iterator. */
  consoleAll?: (o: ConsoleSurface, input: ScenarioInput) => AsyncIterable<unknown>
}

/** operationId to its SDK calls, generated by SdkGen. */
export type DispatchTable = Record<string, DispatchEntry>
