/**
 * The prebuild step of orvano.dev (spec 0011), run before `astro dev` and `astro build`. It reads the contract's
 * generated files and writes what the site renders from them, all gitignored:
 *
 * - `src/content/docs/errors/`: a page per code in `contract/dist/errors.json`, each with its hand written
 *   `src/content/error-fixes/<code>.mdx`, plus the index of every code (AC-17).
 * - `.generated/openapi.docs.json`: a copy of `contract/dist/openapi.public.json` with an `x-codeSamples` tab per SDK
 *   from `contract/dist/examples/`, and each operation's audience and API key scope in its description (AC-15).
 *
 * It fails when a code has no fix file, a fix file has no code or lacks its two sections, or an API reference tag has
 * no guide page linking to one of its operations (AC-17, AC-18). The contract files are never edited.
 *
 *   node scripts/prepare.ts
 */
import { slug } from 'github-slugger'
import { existsSync } from 'node:fs'
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join, relative, resolve } from 'node:path'

const website = resolve(import.meta.dirname, '..')
const repoRoot = dirname(website)
const contractDist = join(repoRoot, 'contract/dist')
const docsDir = join(website, 'src/content/docs')
const errorsDir = join(docsDir, 'errors')
const fixesDir = join(website, 'src/content/error-fixes')
const generatedDir = join(website, '.generated')

/** The API reference's base path; `astro.config.mjs` passes the same one to starlight-openapi. */
const apiBase = 'docs/api'

const problems: string[] = []

// ---------------------------------------------------------------------------------------------------------------------
// Error pages (AC-17)

interface ErrorEntry {
  code: string
  status: number
  description: string
}

async function writeErrorPages(): Promise<void> {
  const errors = JSON.parse(
    await readFile(join(contractDist, 'errors.json'), 'utf8'),
  ) as ErrorEntry[]
  const codes = new Set(errors.map((error) => error.code))

  const fixes = new Map<string, string>()
  for (const file of await readdir(fixesDir)) {
    if (!file.endsWith('.mdx')) continue
    const code = file.slice(0, -'.mdx'.length)
    if (!codes.has(code)) {
      problems.push(
        `src/content/error-fixes/${file} matches no code in contract/dist/errors.json. Delete or rename it.`,
      )
      continue
    }
    const text = (await readFile(join(fixesDir, file), 'utf8')).trim()
    for (const heading of ['## Why it happens', '## How to fix']) {
      if (!text.split('\n').includes(heading))
        problems.push(`src/content/error-fixes/${file} needs a "${heading}" section.`)
    }
    fixes.set(code, text)
  }
  for (const { code } of errors) {
    if (!fixes.has(code))
      problems.push(
        `The error code ${code} has no fix file. Write src/content/error-fixes/${code}.mdx with "## Why it happens" and "## How to fix".`,
      )
  }

  await rm(errorsDir, { recursive: true, force: true })
  await mkdir(errorsDir, { recursive: true })
  for (const error of errors) {
    await writeFile(
      join(errorsDir, `${error.code}.mdx`),
      errorPage(error, fixes.get(error.code) ?? ''),
    )
  }
  await writeFile(join(errorsDir, 'index.mdx'), errorIndex(errors))
}

function errorPage({ code, status, description }: ErrorEntry, fix: string): string {
  const constant = camelCase(code)
  const pascal = constant.charAt(0).toUpperCase() + constant.slice(1)
  return `---
title: ${code}
description: ${JSON.stringify(description)}
editUrl: https://github.com/orvanohq/orvano/edit/main/website/src/content/error-fixes/${code}.mdx
---

{/* Generated by scripts/prepare.ts from contract/dist/errors.json and src/content/error-fixes/${code}.mdx. Edit those. */}

import { Code, TabItem, Tabs } from '@astrojs/starlight/components'

**HTTP status**: ${String(status)} · **Code**: \`${code}\`

${description}

${fix}

## Catch it in your code

Every SDK throws one error type for a failed call. Match on its \`code\`, which is always \`${code}\` for this error, never on the message.

<Tabs syncKey="sdk">
  <TabItem label="JavaScript and Next.js">
    <Code lang="ts" code={${JSON.stringify(`import { ErrorCode, OrvanoError } from '@orvano/js'

try {
  // your Orvano call
} catch (error) {
  if (error instanceof OrvanoError && error.code === ErrorCode.${constant}) {
    // handle ${code}
  } else {
    throw error
  }
}`)}} />
  </TabItem>
  <TabItem label="Dart and Flutter">
    <Code lang="dart" code={${JSON.stringify(`import 'package:orvano_flutter/orvano_flutter.dart'; // or orvano_dart on a server

try {
  // your Orvano call
} on OrvanoException catch (error) {
  if (error.code != ErrorCode.${constant}) rethrow;
  // handle ${code}
}`)}} />
  </TabItem>
  <TabItem label=".NET">
    <Code lang="csharp" code={${JSON.stringify(`using Orvano;

try
{
    // your Orvano call
}
catch (OrvanoException error) when (error.Code == ErrorCode.${pascal})
{
    // handle ${code}
}`)}} />
  </TabItem>
</Tabs>

The error also carries the HTTP status (${String(status)}), a message, and a request ID. Quote the request ID when you report a problem: the server logs it with the failure. See [Errors](/docs/concepts/errors/) for how errors work in every SDK, or [every error code](/errors/).
`
}

function errorIndex(errors: ErrorEntry[]): string {
  const rows = [...errors]
    .sort((a, b) => a.code.localeCompare(b.code))
    .map(
      ({ code, status, description }) =>
        `| [\`${code}\`](/errors/${code}/) | ${String(status)} | ${description.replaceAll('|', '\\|')} |`,
    )
  return `---
title: Error codes
description: "Every error code the Orvano API sends, what causes it, and how to fix it."
---

{/* Generated by scripts/prepare.ts from contract/dist/errors.json. */}

When a call fails, Orvano answers with a problem details body whose \`type\` is the link to the code's page here, for example \`https://orvano.dev/errors/user_not_found\`. Every SDK throws one error type with that \`code\`; [Errors](/docs/concepts/errors/) explains how to catch it.

| Code | HTTP status | What it means |
|---|---|---|
${rows.join('\n')}
`
}

function camelCase(code: string): string {
  return code.replace(/_([a-z0-9])/g, (_, letter: string) => letter.toUpperCase())
}

// ---------------------------------------------------------------------------------------------------------------------
// API reference (AC-15, AC-18)

interface OpenApiOperation {
  operationId: string
  description?: string
  tags?: string[]
  'x-orvano-audience'?: string
  'x-orvano-scope'?: string
  'x-codeSamples'?: { lang: string; label: string; source: string }[]
}

interface OpenApiDocument {
  tags?: { name: string }[]
  paths: Record<string, Record<string, OpenApiOperation>>
}

/** The SDK tabs on every operation page, in this order, with the file extension SdkGen writes for each. */
const sdks = [
  { folder: 'js', ext: 'ts', lang: 'ts', label: 'JavaScript' },
  { folder: 'nextjs', ext: 'tsx', lang: 'tsx', label: 'Next.js' },
  { folder: 'flutter', ext: 'dart', lang: 'dart', label: 'Flutter' },
  { folder: 'dart', ext: 'dart', lang: 'dart', label: 'Dart server' },
  { folder: 'dotnet', ext: 'cs', lang: 'csharp', label: '.NET' },
] as const

const audiences: Record<string, string> = {
  client:
    '**Client SDKs**: JavaScript in the browser, Next.js, and Flutter call it for the signed in user, or with no credential.',
  server: '**Server SDKs**: JavaScript on a server, Dart, and .NET call it with an API key.',
  both: "**Client and server SDKs**: a signed in user's access token, or a server SDK on behalf of one.",
}

async function writeDocsOpenApi(): Promise<void> {
  const document = JSON.parse(
    await readFile(join(contractDist, 'openapi.public.json'), 'utf8'),
  ) as OpenApiDocument

  const tagOfSlug = new Map<string, string>()
  for (const methods of Object.values(document.paths)) {
    for (const operation of Object.values(methods)) {
      const samples = []
      for (const sdk of sdks) {
        const file = join(
          contractDist,
          'examples',
          sdk.folder,
          `${operation.operationId}.${sdk.ext}`,
        )
        if (!existsSync(file)) continue
        const source = (await readFile(file, 'utf8')).replace(
          /^\/\/ Generated by Orvano SdkGen\. Do not edit\.\n/,
          '',
        )
        samples.push({ lang: sdk.lang, label: sdk.label, source: source.trimEnd() })
      }
      if (samples.length > 0) operation['x-codeSamples'] = samples

      const audience = operation['x-orvano-audience'] ?? ''
      const notes = [audiences[audience] ?? `**Audience**: ${audience}.`]
      const scope = operation['x-orvano-scope']
      if (scope !== undefined) notes.push(`**API key scope**: \`${scope}\`.`)
      notes.push(
        'A failure answers with a problem details body; its `code` has a page under [Errors](/errors/).',
      )
      operation.description = [operation.description ?? '', notes.join(' ')]
        .filter(Boolean)
        .join('\n\n')

      for (const tag of operation.tags ?? []) tagOfSlug.set(slug(operation.operationId), tag)
    }
  }

  await mkdir(generatedDir, { recursive: true })
  await writeFile(join(generatedDir, 'openapi.docs.json'), `${JSON.stringify(document, null, 2)}\n`)

  // AC-18: every link to an operation names a real one (the links validator can't see these routes), and every tag in
  // the reference has a hand written page that links to one of its operations.
  const linked = new Set<string>()
  const linkPattern = new RegExp(`/${apiBase}/operations/([^/#)\\s"'\`]*)`, 'g')
  for (const file of [
    ...(await listPages(join(docsDir, 'docs'))),
    ...(await listPages(fixesDir)),
  ]) {
    for (const match of (await readFile(file, 'utf8')).matchAll(linkPattern)) {
      const tag = tagOfSlug.get(match[1] ?? '')
      if (tag === undefined)
        problems.push(
          `${relative(website, file)} links to ${match[0]}, which is no operation in the API reference.`,
        )
      else linked.add(tag)
    }
  }
  for (const { name } of document.tags ?? []) {
    if (!linked.has(name)) {
      const example = [...tagOfSlug].find(([, tag]) => tag === name)?.[0] ?? '<operation>'
      problems.push(
        `No guide links to the API reference for the "${name}" tag. Link one of its operations from a page under src/content/docs/docs/, for example /${apiBase}/operations/${example}/.`,
      )
    }
  }
}

async function listPages(dir: string): Promise<string[]> {
  const pages: string[] = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) pages.push(...(await listPages(path)))
    else if (/\.mdx?$/.test(entry.name)) pages.push(path)
  }
  return pages
}

// ---------------------------------------------------------------------------------------------------------------------

await writeErrorPages()
await writeDocsOpenApi()

if (problems.length > 0) {
  for (const problem of problems) console.error(`✗ ${problem}`)
  process.exit(1)
}
console.log(
  `Prepared ${relative(website, errorsDir)}/ and ${relative(website, generatedDir)}/openapi.docs.json.`,
)
