using Scriban;
using Scriban.Runtime;

namespace Orvano.SdkGen.Rendering;

/// <summary>
/// Renders the Scriban templates under <c>templates/&lt;lang&gt;/</c>. View model members are
/// exposed in snake_case (<c>ClassName</c> becomes <c>class_name</c>).
/// </summary>
internal sealed class TemplateRenderer(string templateRoot)
{
    /// <summary>The first line of every generated file.</summary>
    public const string Header = "Generated by Orvano SdkGen. Do not edit.";

    private readonly Dictionary<string, Template> _cache = new(StringComparer.Ordinal);

    public string Render(string language, string name, object model)
    {
        var key = $"{language}/{name}";
        if (!_cache.TryGetValue(key, out var template))
        {
            var path = Path.Combine(templateRoot, language, name + ".scriban");
            template = Template.Parse(File.ReadAllText(path), path);
            if (template.HasErrors) throw new InvalidOperationException($"{path}: {string.Join("; ", template.Messages)}");
            _cache[key] = template;
        }

        var globals = new ScriptObject();
        globals.Import(model);
        globals.SetValue("header", Header, readOnly: true);
        var context = new TemplateContext { StrictVariables = true, LoopLimit = 0 };
        context.PushGlobal(globals);
        return template.Render(context);
    }
}
