/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInstallRouteImport } from './routes/_app/install'
import { Route as DevComponentsRouteImport } from './routes/dev.components'
import { Route as AppOrgsIndexRouteImport } from './routes/_app/orgs/index'
import { Route as AppOrgsOrgIdRouteRouteImport } from './routes/_app/orgs/$orgId/route'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/_app/projects/$projectId/route'
import { Route as AppOrgsOrgIdIndexRouteImport } from './routes/_app/orgs/$orgId/index'
import { Route as AppOrgsOrgIdMembersRouteImport } from './routes/_app/orgs/$orgId/members'
import { Route as AppOrgsOrgIdSettingsRouteImport } from './routes/_app/orgs/$orgId/settings'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdEmailRouteRouteImport } from './routes/_app/projects/$projectId/email/route'
import { Route as AppProjectsProjectIdKeysRouteImport } from './routes/_app/projects/$projectId/keys'
import { Route as AppProjectsProjectIdPlatformsRouteImport } from './routes/_app/projects/$projectId/platforms'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app/projects/$projectId/settings'
import { Route as AppProjectsProjectIdEmailIndexRouteImport } from './routes/_app/projects/$projectId/email/index'
import { Route as AppProjectsProjectIdEmailSettingsRouteImport } from './routes/_app/projects/$projectId/email/settings'
import { Route as AppProjectsProjectIdUsersIndexRouteImport } from './routes/_app/projects/$projectId/users/index'
import { Route as AppProjectsProjectIdUsersUserIdRouteImport } from './routes/_app/projects/$projectId/users/$userId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallRoute = AppInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => AppRoute,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsOrgIdRouteRoute = AppOrgsOrgIdRouteRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrgsOrgIdIndexRoute = AppOrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgsOrgIdRouteRoute,
} as any)
const AppOrgsOrgIdMembersRoute = AppOrgsOrgIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppOrgsOrgIdRouteRoute,
} as any)
const AppOrgsOrgIdSettingsRoute = AppOrgsOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgsOrgIdRouteRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdEmailRouteRoute =
  AppProjectsProjectIdEmailRouteRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdKeysRoute =
  AppProjectsProjectIdKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdPlatformsRoute =
  AppProjectsProjectIdPlatformsRouteImport.update({
    id: '/platforms',
    path: '/platforms',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdEmailIndexRoute =
  AppProjectsProjectIdEmailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdEmailRouteRoute,
  } as any)
const AppProjectsProjectIdEmailSettingsRoute =
  AppProjectsProjectIdEmailSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdEmailRouteRoute,
  } as any)
const AppProjectsProjectIdUsersIndexRoute =
  AppProjectsProjectIdUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdUsersUserIdRoute =
  AppProjectsProjectIdUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/invite': typeof InviteRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/install': typeof AppInstallRoute
  '/dev/components': typeof DevComponentsRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdRouteRouteWithChildren
  '/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/orgs/': typeof AppOrgsIndexRoute
  '/projects/$projectId/email': typeof AppProjectsProjectIdEmailRouteRouteWithChildren
  '/orgs/$orgId/members': typeof AppOrgsOrgIdMembersRoute
  '/orgs/$orgId/settings': typeof AppOrgsOrgIdSettingsRoute
  '/projects/$projectId/keys': typeof AppProjectsProjectIdKeysRoute
  '/projects/$projectId/platforms': typeof AppProjectsProjectIdPlatformsRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/email/settings': typeof AppProjectsProjectIdEmailSettingsRoute
  '/projects/$projectId/users/$userId': typeof AppProjectsProjectIdUsersUserIdRoute
  '/projects/$projectId/email/': typeof AppProjectsProjectIdEmailIndexRoute
  '/projects/$projectId/users/': typeof AppProjectsProjectIdUsersIndexRoute
}
export interface FileRoutesByTo {
  '/invite': typeof InviteRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/install': typeof AppInstallRoute
  '/dev/components': typeof DevComponentsRoute
  '/': typeof AppIndexRoute
  '/orgs': typeof AppOrgsIndexRoute
  '/orgs/$orgId/members': typeof AppOrgsOrgIdMembersRoute
  '/orgs/$orgId/settings': typeof AppOrgsOrgIdSettingsRoute
  '/projects/$projectId/keys': typeof AppProjectsProjectIdKeysRoute
  '/projects/$projectId/platforms': typeof AppProjectsProjectIdPlatformsRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/email/settings': typeof AppProjectsProjectIdEmailSettingsRoute
  '/projects/$projectId/users/$userId': typeof AppProjectsProjectIdUsersUserIdRoute
  '/projects/$projectId/email': typeof AppProjectsProjectIdEmailIndexRoute
  '/projects/$projectId/users': typeof AppProjectsProjectIdUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/invite': typeof InviteRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/install': typeof AppInstallRoute
  '/dev/components': typeof DevComponentsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/orgs/$orgId': typeof AppOrgsOrgIdRouteRouteWithChildren
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/_app/orgs/': typeof AppOrgsIndexRoute
  '/_app/projects/$projectId/email': typeof AppProjectsProjectIdEmailRouteRouteWithChildren
  '/_app/orgs/$orgId/members': typeof AppOrgsOrgIdMembersRoute
  '/_app/orgs/$orgId/settings': typeof AppOrgsOrgIdSettingsRoute
  '/_app/projects/$projectId/keys': typeof AppProjectsProjectIdKeysRoute
  '/_app/projects/$projectId/platforms': typeof AppProjectsProjectIdPlatformsRoute
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/_app/orgs/$orgId/': typeof AppOrgsOrgIdIndexRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/email/settings': typeof AppProjectsProjectIdEmailSettingsRoute
  '/_app/projects/$projectId/users/$userId': typeof AppProjectsProjectIdUsersUserIdRoute
  '/_app/projects/$projectId/email/': typeof AppProjectsProjectIdEmailIndexRoute
  '/_app/projects/$projectId/users/': typeof AppProjectsProjectIdUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/install'
    | '/dev/components'
    | '/orgs/$orgId'
    | '/projects/$projectId'
    | '/orgs/'
    | '/projects/$projectId/email'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/settings'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/platforms'
    | '/projects/$projectId/settings'
    | '/orgs/$orgId/'
    | '/projects/$projectId/'
    | '/projects/$projectId/email/settings'
    | '/projects/$projectId/users/$userId'
    | '/projects/$projectId/email/'
    | '/projects/$projectId/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/install'
    | '/dev/components'
    | '/'
    | '/orgs'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/settings'
    | '/projects/$projectId/keys'
    | '/projects/$projectId/platforms'
    | '/projects/$projectId/settings'
    | '/orgs/$orgId'
    | '/projects/$projectId'
    | '/projects/$projectId/email/settings'
    | '/projects/$projectId/users/$userId'
    | '/projects/$projectId/email'
    | '/projects/$projectId/users'
  id:
    | '__root__'
    | '/_app'
    | '/invite'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/_app/install'
    | '/dev/components'
    | '/_app/'
    | '/_app/orgs/$orgId'
    | '/_app/projects/$projectId'
    | '/_app/orgs/'
    | '/_app/projects/$projectId/email'
    | '/_app/orgs/$orgId/members'
    | '/_app/orgs/$orgId/settings'
    | '/_app/projects/$projectId/keys'
    | '/_app/projects/$projectId/platforms'
    | '/_app/projects/$projectId/settings'
    | '/_app/orgs/$orgId/'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/email/settings'
    | '/_app/projects/$projectId/users/$userId'
    | '/_app/projects/$projectId/email/'
    | '/_app/projects/$projectId/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  InviteRoute: typeof InviteRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DevComponentsRoute: typeof DevComponentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/install': {
      id: '/_app/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof AppInstallRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orgs/': {
      id: '/_app/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$orgId': {
      id: '/_app/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AppOrgsOrgIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$orgId/': {
      id: '/_app/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AppOrgsOrgIdIndexRouteImport
      parentRoute: typeof AppOrgsOrgIdRouteRoute
    }
    '/_app/orgs/$orgId/members': {
      id: '/_app/orgs/$orgId/members'
      path: '/members'
      fullPath: '/orgs/$orgId/members'
      preLoaderRoute: typeof AppOrgsOrgIdMembersRouteImport
      parentRoute: typeof AppOrgsOrgIdRouteRoute
    }
    '/_app/orgs/$orgId/settings': {
      id: '/_app/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AppOrgsOrgIdSettingsRouteImport
      parentRoute: typeof AppOrgsOrgIdRouteRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/email': {
      id: '/_app/projects/$projectId/email'
      path: '/email'
      fullPath: '/projects/$projectId/email'
      preLoaderRoute: typeof AppProjectsProjectIdEmailRouteRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/keys': {
      id: '/_app/projects/$projectId/keys'
      path: '/keys'
      fullPath: '/projects/$projectId/keys'
      preLoaderRoute: typeof AppProjectsProjectIdKeysRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/platforms': {
      id: '/_app/projects/$projectId/platforms'
      path: '/platforms'
      fullPath: '/projects/$projectId/platforms'
      preLoaderRoute: typeof AppProjectsProjectIdPlatformsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/email/': {
      id: '/_app/projects/$projectId/email/'
      path: '/'
      fullPath: '/projects/$projectId/email/'
      preLoaderRoute: typeof AppProjectsProjectIdEmailIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdEmailRouteRoute
    }
    '/_app/projects/$projectId/email/settings': {
      id: '/_app/projects/$projectId/email/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/email/settings'
      preLoaderRoute: typeof AppProjectsProjectIdEmailSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdEmailRouteRoute
    }
    '/_app/projects/$projectId/users/': {
      id: '/_app/projects/$projectId/users/'
      path: '/users'
      fullPath: '/projects/$projectId/users/'
      preLoaderRoute: typeof AppProjectsProjectIdUsersIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/users/$userId': {
      id: '/_app/projects/$projectId/users/$userId'
      path: '/users/$userId'
      fullPath: '/projects/$projectId/users/$userId'
      preLoaderRoute: typeof AppProjectsProjectIdUsersUserIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
  }
}

interface AppOrgsOrgIdRouteRouteChildren {
  AppOrgsOrgIdMembersRoute: typeof AppOrgsOrgIdMembersRoute
  AppOrgsOrgIdSettingsRoute: typeof AppOrgsOrgIdSettingsRoute
  AppOrgsOrgIdIndexRoute: typeof AppOrgsOrgIdIndexRoute
}

const AppOrgsOrgIdRouteRouteChildren: AppOrgsOrgIdRouteRouteChildren = {
  AppOrgsOrgIdMembersRoute: AppOrgsOrgIdMembersRoute,
  AppOrgsOrgIdSettingsRoute: AppOrgsOrgIdSettingsRoute,
  AppOrgsOrgIdIndexRoute: AppOrgsOrgIdIndexRoute,
}

const AppOrgsOrgIdRouteRouteWithChildren =
  AppOrgsOrgIdRouteRoute._addFileChildren(AppOrgsOrgIdRouteRouteChildren)

interface AppProjectsProjectIdEmailRouteRouteChildren {
  AppProjectsProjectIdEmailSettingsRoute: typeof AppProjectsProjectIdEmailSettingsRoute
  AppProjectsProjectIdEmailIndexRoute: typeof AppProjectsProjectIdEmailIndexRoute
}

const AppProjectsProjectIdEmailRouteRouteChildren: AppProjectsProjectIdEmailRouteRouteChildren =
  {
    AppProjectsProjectIdEmailSettingsRoute:
      AppProjectsProjectIdEmailSettingsRoute,
    AppProjectsProjectIdEmailIndexRoute: AppProjectsProjectIdEmailIndexRoute,
  }

const AppProjectsProjectIdEmailRouteRouteWithChildren =
  AppProjectsProjectIdEmailRouteRoute._addFileChildren(
    AppProjectsProjectIdEmailRouteRouteChildren,
  )

interface AppProjectsProjectIdRouteRouteChildren {
  AppProjectsProjectIdEmailRouteRoute: typeof AppProjectsProjectIdEmailRouteRouteWithChildren
  AppProjectsProjectIdKeysRoute: typeof AppProjectsProjectIdKeysRoute
  AppProjectsProjectIdPlatformsRoute: typeof AppProjectsProjectIdPlatformsRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdUsersUserIdRoute: typeof AppProjectsProjectIdUsersUserIdRoute
  AppProjectsProjectIdUsersIndexRoute: typeof AppProjectsProjectIdUsersIndexRoute
}

const AppProjectsProjectIdRouteRouteChildren: AppProjectsProjectIdRouteRouteChildren =
  {
    AppProjectsProjectIdEmailRouteRoute:
      AppProjectsProjectIdEmailRouteRouteWithChildren,
    AppProjectsProjectIdKeysRoute: AppProjectsProjectIdKeysRoute,
    AppProjectsProjectIdPlatformsRoute: AppProjectsProjectIdPlatformsRoute,
    AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
    AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
    AppProjectsProjectIdUsersUserIdRoute: AppProjectsProjectIdUsersUserIdRoute,
    AppProjectsProjectIdUsersIndexRoute: AppProjectsProjectIdUsersIndexRoute,
  }

const AppProjectsProjectIdRouteRouteWithChildren =
  AppProjectsProjectIdRouteRoute._addFileChildren(
    AppProjectsProjectIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppInstallRoute: typeof AppInstallRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrgsOrgIdRouteRoute: typeof AppOrgsOrgIdRouteRouteWithChildren
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRouteWithChildren
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInstallRoute: AppInstallRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrgsOrgIdRouteRoute: AppOrgsOrgIdRouteRouteWithChildren,
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRouteWithChildren,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  InviteRoute: InviteRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DevComponentsRoute: DevComponentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
